export enum Paths {
  ROOT = '/',
  AUTH = 'auth',
  LOGIN = 'login',
  REGISTER = 'register',
  DASHBOARD = 'dashboard',
  HOME = 'home',
  USERS = 'users',
  STUDENTS = 'students',
  COURSES = 'courses',
  ENROLLMENTS = 'enrollments',
  PROFESORS = 'professors',
  DETAILS = 'details',
  ID = ':id',
}
